version: 2
jobs:
  build:
    working_directory: ~/ohm-str
    docker:
      - image: circleci/node:10-browsers
    steps:
      # Checkout code from branch into WD
      - checkout
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Restore local dependencies from cache
      - restore_cache:
          key: ohm-str-{{ .Branch }}-{{ checksum "package-lock.json" }}
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install
      # Cache local dependencies if they don't exist
      - save_cache:
          key: ohm-str-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      # Test the source code
      - run:
          name: Testing
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      # End-to-end tests
      - run:
          name: End to end tests
          command: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
        